version: "3"

tasks:
  test:
    cmds:
      - python3 -m unittest discover -p 'test_*.py' {{.CLI_ARGS}}

  mypy:
    desc: Run mypy tests
    cmds:
      - mypy --exclude .venv .

  flake8:
    cmds:
      - flake8 typelog

  format:
    desc: To format with black and remove not needed imported libraries
    cmds:
      - rm -R typelog-stubs | true
      - black .
      - isort --profile black -sl --skip .venv .
      - autoflake --remove-all-unused-imports --ignore-init-module-imports -i -r --exclude .venv .
      - isort -m 3 --skip .venv .
      - task: flake8
      - task: mypy

  dev:install:
    cmds:
      - pip install -r requirements/requirements.dev.txt

  build:install:
    cmds:
      - pip install setuptools build twine

  build:build:
    cmds:
      - rm -R dist | true
      - rm -R typelog.egg-info | true
      - rm -R typelog-stubs | true
      - stubgen typelog -o stubs && mv stubs/typelog typelog-stubs && rm -R stubs
      - python3 stubgen_fix.py
      - python3 -m build

  build:check:
    cmds:
      - twine check dist/*

  build:upload:test:
    cmds:
      - twine upload --repository testpypi dist/*

  build:upload:prod:
    cmds:
      - twine upload --repository pypi dist/*
